version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r Blacklists/requirements.txt
  build:
    commands:
      - echo "Ejecutando pruebas unitarias..."
      - python -m unittest discover -s Blacklists -v
artifacts:
  files:
    - '**/*'